# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('address3', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('option 1', 'UK'), ('option 2', 'USA')], default='UK', max_length=10)),
                ('child_first_name', models.CharField(max_length=50)),
                ('child_last_name', models.CharField(max_length=50)),
                ('child_address', models.CharField(max_length=250)),
                ('child_address2', models.CharField(blank=True, max_length=250, null=True)),
                ('child_address3', models.CharField(blank=True, max_length=250, null=True)),
                ('child_postal_code', models.CharField(max_length=20)),
                ('child_city', models.CharField(max_length=100)),
                ('child_country', models.CharField(choices=[('option 1', 'UK'), ('option 2', 'USA')], default='UK', max_length=10)),
                ('child_boy_girl', models.CharField(choices=[('M', 'Boy'), ('F', 'Girl')], default='Boy', max_length=10)),
                ('child_age', models.IntegerField()),
                ('child_birth_year', models.IntegerField(default=2013)),
                ('child_birth_month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=1, max_length=10)),
                ('child_birth_day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default=1, max_length=10)),
                ('child_age_time', models.CharField(choices=[('YS', 'Years'), ('Y', 'Year'), ('MS', 'Months'), ('M', 'Month'), ('D', 'Days')], default='Years', max_length=10)),
                ('child_relative_name', models.CharField(max_length=50)),
                ('child_friend_name', models.CharField(max_length=50)),
                ('child_present', models.CharField(max_length=200)),
                ('child_achievement', models.CharField(max_length=200)),
                ('letter_design', models.CharField(choices=[('1', 'letter1'), ('2', 'letter2'), ('3', 'letter3'), ('4', 'letter4'), ('5', 'letter5')], default='1', max_length=10)),
                ('delivery_date', models.CharField(choices=[('1', 'Monday 6th Nov 2017'), ('2', 'Monday 13th Nov 2017'), ('3', 'Monday 20th Nov 2017'), ('4', 'Monday 27th Nov 2017'), ('5', 'Monday 04th Dec 2017'), ('6', 'Monday 11th Dec 2017'), ('7', 'Monday 18th Dec 2017')], default='1', max_length=10)),
                ('pdf_download', models.BooleanField(default=False)),
                ('agree_terms', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product')),
            ],
        ),
    ]
