# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pdf_download',
            field=models.BooleanField(default=False),
        ),
    ]
