# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='child_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
