# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(db_index=True, default='TEMP', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='child_age_time',
            field=models.CharField(choices=[('Years', 'Years'), ('Year', 'Year'), ('Month', 'Months'), ('Month', 'Month'), ('Days', 'Days')], default='Years', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='child_country',
            field=models.CharField(choices=[('UK', 'UK'), ('USA', 'USA')], default='UK', max_length=10),
        ),
    ]
