# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171106_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sender_email',
            field=models.EmailField(default='sender', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sender_first_name',
            field=models.CharField(default='sender', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sender_last_name',
            field=models.CharField(default='email', max_length=50),
            preserve_default=False,
        ),
    ]
