# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171103_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(blank=True, default='blank', max_length=32, null=True),
        ),
    ]
