# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0003_auto_20171106_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_option_id', to='orders.OrderItem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_option', to='shop.Product')),
            ],
        ),
    ]
